orb_slam2_rgbd:
  ros__parameters:

    publish_pointcloud: true
    publish_pose: true
    localize_only: false
    reset_map: false

    # static parameters
    load_map: false
    map_file: map.bin

    pointcloud_frame_id: map
    camera_frame_id: odom #camera_link
    min_num_kf_in_map: 5

    #ORB parameters
    ORBextractor/nFeatures: 1000
    ORBextractor/scaleFactor: 1.2
    ORBextractor/nLevels: 8
    ORBextractor/iniThFAST: 20
    ORBextractor/minThFAST: 7

    #Camera Parameters
    # Camera calibration and distortion parameters (OpenCV) 
    Camera.fx: 535.4
    Camera.fy: 539.2
    Camera.cx: 320.1
    Camera.cy: 247.6

    Camera.k1: 0.0
    Camera.k2: 0.0
    Camera.p1: 0.0
    Camera.p2: 0.0

    Camera.width: 640
    Camera.height: 480

    #Camera frames per second
    camera_fps: 30
    #Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale) 
    camera_rgb_encoding: true
    #Close/Far threshold. Baseline times.
    ThDepth: 40.0
    depth_map_factor: 1.0
    camera_baseline: 9.052
